### ISSUE TITLE
Full Disk Access

### ISSUE THREAD

**Issue by kilabyte** [airmessage/airmessage-server-legacy#1]
Hello i installed 3.4 and it keeps complaining about needed full disk access despite have it enabled in the settings. Am i missing something here?

**Comment by tagavari** [comment]
If you're upgrading from AirMessage 0.3, please try dtagging the AirMessage app to the full disk access list, and restarting your computer.

**Comment by kilabyte** [comment]
that seems to have work but now the app says it wont connect. Do i have to connect via google with the latest version or can i continue with the manual setup?

**Comment by kilabyte** [comment]
looks like i had to join the beta program on android. all is well now thank you.
