### ISSUE TITLE
Air message server not requesting automation privileges and can't send messages

### ISSUE THREAD

**Issue by deweller** [airmessage/airmessage-server-legacy#2]
On Mac OS X 11.4 (20F71), there is no way to grant automation privileges to AirMessage.

Under System Preferences > Security & Privacy > Privacy > Automation, AirMessage does not show up as one of the apps requesting automation privileges.

When I attempt to send a message from my Android device, I get the error 51:53: syntax error: Expected end of line by found property.  (-2741).

**Comment by tagavari** [comment]
That's an AppleScript execution error, and failure to properly run AppleScript is likely why AirMessage isn't even listed as an app for Automation access.

There are a number of circumstances that could cause this to happen. [The first result for a web search for "Expected end of line by found property" brings up this result](https://stackoverflow.com/questions/22847583/applescript-expected-end-of-line-but-found-property-error-when-using-google-c), which talks about Parallels interfering with AppleScript. Is it possible that you're experiencing a similar issue?

**Comment by deweller** [comment]
Thanks for looking into this.  I've never run Parallels on this machine.  This is an M1 Mac.

Is there a way for me to debug why AirMessage won't run AppleScript?

**Comment by deweller** [comment]
I just tried upgrading to native silicon server 3.2.1.  When I launch, I see `AirMessage Server does not have permission to read your messages`.  I granted the app the Full Disk Access in system preferences, but I still see this message even after restarting the app.

**Comment by tagavari** [comment]
I've tested AirMessage on an M1 Mac myself, so I don't believe it would be an issue related to that.

Could you try removing and adding AirMessage to the Full Disk Access list, and restarting your computer?

**Comment by deweller** [comment]
A restart fixed the Full Disk Access issue.

I still see `51:53: syntax error: Expected end of line but found property. (-2741)` when I try to send messages from my Android device.  I can receive messages on my Android phone.

Is there any way to debug this further?  Is there a way to enable logging in AirMessage.cfg?

**Comment by tagavari** [comment]
AirMessage's log files are located at `~/Library/Application Support/AirMessage/logs/latest.log`. However, I'm not sure if there will be anything of interest there - that error message you received is about all that AppleScript reports.

As a troubleshooting step, could you try running [this script](https://github.com/airmessage/airmessage-server/files/6796835/getAllMessages.txt) in Terminal with `$ osascript getAllMessages.txt`? Feel free it inspect it, it's just a script that fetches the first conversation in Messages.

**Comment by bhyde** [comment]
When I upgraded to 3.2.1 (after upgrading my intel mac to Big Sur) I also struggled.  It took a while to puzzle out how successfully grant it full disk access.  I had to exit AirMessage, remove it from list of things with full disk access, drag it to the trash, reboot, reinstall it, and add it back (by dragging the app into the appropriate pane in the "Security & Privacy" preferences.  After that I needed to grant it permission to remote control Messages.  Presumably some of that was unnecessary, but I'd tried a lot of things before doing that.

I didn't encounter "syntax error: Expected end of line but found property" outlined above, so that's nice.

Thanks for the work on this!

**Comment by deweller** [comment]
I dragged the application to the trash and re-downloaded the application.  I then dragged the application into the Full Disk Access pane before I launched it.

This time it worked.  I am now able to receive and send message from my Android device.

I'm baffled as to what is different now, but it does work.  Thanks for your help.
