### ISSUE TITLE
hopeto develop iPhone Tweak

### ISSUE THREAD

**Issue by theBillLee** [airmessage/airmessage-server-legacy#6]

**Comment by tagavari** [comment]
Thank you for the request. There are no plans to bring AirMessage Server to jailbroken iOS devices - focusing only on macOS makes it easier to maintain a more user-friendly and seamless experience.

However, @SixDigitCode has developed a program called [AirBridge](https://github.com/SixDigitCode/AirBridge) which allows AirMessage to communicate with [SMServer](https://github.com/iandwelker/smserver), which I do recommend you take a look at. Here's the announcement post: [https://redd.it/p4db50](https://redd.it/p4db50)

**Comment by theBillLee** [comment]
Thank you for dev AirMessage Server, love it very  much
